// This file will be auto-generated by `pnpm db:generate`
// Run: supabase gen types typescript --local > packages/database/src/types.ts
//
// Placeholder type until Supabase is initialized
export type Database = Record<string, never>;
